ClearExistingRules:
  in: query
  name: clearExistingRules
  required: false
  schema:
    type: boolean
  description: Indicates whether existing rules should be deleted before adding this batch.

ObjectIDRule:
  in: path
  name: objectID
  description: Unique identifier of a rule object.
  example: 'a-rule-id'
  required: true
  schema:
    type: string

query:
  type: string
  description: Rule object query.
  default: ''
