/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.monitoring

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * ProbesMetric
 *
 * @param t Timestamp in [Unix epoch time](https://wikipedia.org/wiki/Unix_time) in milliseconds.
 * @param v Value of the metric.
 */
@Serializable
public data class ProbesMetric(

  /** Timestamp in [Unix epoch time](https://wikipedia.org/wiki/Unix_time) in milliseconds. */
  @SerialName(value = "t") val t: Long? = null,

  /** Value of the metric. */
  @SerialName(value = "v") val v: Int? = null,
)
