// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.monitoring;

import com.fasterxml.jackson.annotation.*;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** LatencyResponseMetrics */
public class LatencyResponseMetrics {

  @JsonProperty("latency")
  private Map<String, List<TimeInner>> latency;

  public LatencyResponseMetrics setLatency(Map<String, List<TimeInner>> latency) {
    this.latency = latency;
    return this;
  }

  public LatencyResponseMetrics putLatency(String key, List<TimeInner> latencyItem) {
    if (this.latency == null) {
      this.latency = new HashMap<>();
    }
    this.latency.put(key, latencyItem);
    return this;
  }

  /**
   * Get latency
   *
   * @return latency
   */
  @javax.annotation.Nullable
  public Map<String, List<TimeInner>> getLatency() {
    return latency;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LatencyResponseMetrics latencyResponseMetrics = (LatencyResponseMetrics) o;
    return Objects.equals(this.latency, latencyResponseMetrics.latency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(latency);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LatencyResponseMetrics {\n");
    sb.append("    latency: ").append(toIndentedString(latency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
