// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element
import 'package:algolia_client_recommend/src/model/trending_facets_model.dart';

import 'package:json_annotation/json_annotation.dart';

part 'base_trending_facets_query.g.dart';

@JsonSerializable()
final class BaseTrendingFacetsQuery {
  /// Returns a new [BaseTrendingFacetsQuery] instance.
  const BaseTrendingFacetsQuery({
    required this.facetName,
    this.model,
  });

  /// Facet name for trending models.
  @JsonKey(name: r'facetName')
  final String facetName;

  @JsonKey(name: r'model')
  final TrendingFacetsModel? model;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BaseTrendingFacetsQuery &&
          other.facetName == facetName &&
          other.model == model;

  @override
  int get hashCode => facetName.hashCode + model.hashCode;

  factory BaseTrendingFacetsQuery.fromJson(Map<String, dynamic> json) =>
      _$BaseTrendingFacetsQueryFromJson(json);

  Map<String, dynamic> toJson() => _$BaseTrendingFacetsQueryToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
