/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * BaseGetApiKeyResponse
 *
 * @param createdAt Time of the event expressed in milliseconds since the Unix epoch.
 * @param `value` The API key.
 */
@Serializable
public data class BaseGetApiKeyResponse(

  /** Time of the event expressed in milliseconds since the Unix epoch. */
  @SerialName(value = "createdAt") val createdAt: Long,

  /** The API key. */
  @SerialName(value = "value") val `value`: String? = null,
)
