/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Defines the ordering of facets (widgets).
 *
 * @param facets
 * @param values Ordering of facet values within an individual facet.
 */
@Serializable
public data class FacetOrdering(

  @SerialName(value = "facets") val facets: Facets? = null,

  /** Ordering of facet values within an individual facet. */
  @SerialName(value = "values") val values: Map<kotlin.String, Value>? = null,
)
