/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * HasPendingMappingsResponse
 *
 * @param pending Indicates whether there are clusters undergoing migration, creation, or deletion.
 * @param clusters Cluster pending mapping state: migrating, creating, deleting.
 */
@Serializable
public data class HasPendingMappingsResponse(

  /** Indicates whether there are clusters undergoing migration, creation, or deletion. */
  @SerialName(value = "pending") val pending: Boolean,

  /** Cluster pending mapping state: migrating, creating, deleting.  */
  @SerialName(value = "clusters") val clusters: Map<kotlin.String, List<String>>? = null,
)
