/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * UserIDs data.
 *
 * @param userIDs List of userIDs.
 */
@Serializable
public data class ListUserIdsResponse(

  /** List of userIDs. */
  @SerialName(value = "userIDs") val userIDs: List<UserId>,
)
