/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.search

import kotlinx.serialization.*

@Serializable
public enum class LogType(public val value: kotlin.String) {

  @SerialName(value = "all")
  All("all"),

  @SerialName(value = "query")
  Query("query"),

  @SerialName(value = "build")
  Build("build"),

  @SerialName(value = "error")
  Error("error");

  override fun toString(): kotlin.String = value
}
