/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Settings for the semantic search part of NeuralSearch. Only used when `mode` is _neuralSearch_.
 *
 * @param eventSources Indices from which to collect click and conversion events. If null, the current index and replica group will be used as the event source.
 */
@Serializable
public data class SemanticSearch(

  /** Indices from which to collect click and conversion events. If null, the current index and replica group will be used as the event source. */
  @SerialName(value = "eventSources") val eventSources: List<String>? = null,
)
