// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.monitoring;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.Objects;

/** IndexingTimeResponse */
public class IndexingTimeResponse {

  @JsonProperty("metrics")
  private IndexingTimeResponseMetrics metrics;

  public IndexingTimeResponse setMetrics(IndexingTimeResponseMetrics metrics) {
    this.metrics = metrics;
    return this;
  }

  /** Get metrics */
  @javax.annotation.Nullable
  public IndexingTimeResponseMetrics getMetrics() {
    return metrics;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndexingTimeResponse indexingTimeResponse = (IndexingTimeResponse) o;
    return Objects.equals(this.metrics, indexingTimeResponse.metrics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metrics);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndexingTimeResponse {\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
