apis:
  abtesting:
    root: specs/abtesting/spec.yml
  analytics:
    root: specs/analytics/spec.yml
  ingestion:
    root: specs/ingestion/spec.yml
  insights:
    root: specs/insights/spec.yml
  monitoring:
    root: specs/monitoring/spec.yml
    rules:
      security-defined: off
  personalization:
    root: specs/personalization/spec.yml
  query-suggestions:
    root: specs/query-suggestions/spec.yml
  recommend:
    root: specs/recommend/spec.yml
  search:
    root: specs/search/spec.yml

extends:
  - recommended

rules:
  info-license: off # for now we can keep it off.
  no-ambiguous-paths: off # this is out of our scope.
  no-enum-type-mismatch: warn # keeping the warning since it only occur on one edge case

  no-identical-paths: error
  tag-description: error
  parameter-description: error
  operation-description: error
  tags-alphabetical: error

  # this rule should only be disabled for the monitoring API, but it's not working right now.
  security-defined: off
