# coding: utf-8

"""
Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
"""

from __future__ import annotations

from enum import Enum
from json import loads
from sys import version_info

if version_info >= (3, 11):
    from typing import Self
else:
    from typing_extensions import Self


class ExternalOrdering(str, Enum):
    """
    Ordering to apply on the injected items coming from the external source. 'default' means the items will be ordered as they are in the index (natural relevance) in the smart group. 'userDefined' means the order in which the objectIDs are provided in the run request payload will be preserved in the smart group.
    """

    """
    allowed enum values
    """
    DEFAULT = "default"

    USERDEFINED = "userDefined"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExternalOrdering from a JSON string"""
        return cls(loads(json_str))
