// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element

import 'package:json_annotation/json_annotation.dart';

part 'assign_user_id_params.g.dart';

@JsonSerializable()
final class AssignUserIdParams {
  /// Returns a new [AssignUserIdParams] instance.
  const AssignUserIdParams({
    required this.cluster,
  });

  /// Name of the cluster.
  @JsonKey(name: r'cluster')
  final String cluster;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssignUserIdParams && other.cluster == cluster;

  @override
  int get hashCode => cluster.hashCode;

  factory AssignUserIdParams.fromJson(Map<String, dynamic> json) =>
      _$AssignUserIdParamsFromJson(json);

  Map<String, dynamic> toJson() => _$AssignUserIdParamsToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
