// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element
import 'package:json_annotation/json_annotation.dart';

/// - `none`: executes all queries. - `stopIfEnoughMatches`: executes queries one by one, stopping further query execution as soon as a query matches at least the `hitsPerPage` number of results.
@JsonEnum(valueField: 'raw')
enum SearchStrategy {
  none(r'none'),
  stopIfEnoughMatches(r'stopIfEnoughMatches');

  const SearchStrategy(this.raw);
  final dynamic raw;

  dynamic toJson() => raw;

  static SearchStrategy fromJson(dynamic json) {
    for (final value in values) {
      if (value.raw == json) return value;
    }
    throw ArgumentError.value(json, "raw", "No enum value with that value");
  }

  @override
  String toString() => raw.toString();
}
