// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element
import 'package:algolia_search/src/model/search_response.dart';

import 'package:json_annotation/json_annotation.dart';

part 'search_responses.g.dart';

@JsonSerializable()
final class SearchResponses {
  /// Returns a new [SearchResponses] instance.
  const SearchResponses({
    required this.results,
  });

  @JsonKey(name: r'results')
  final List<SearchResponse> results;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResponses && other.results == results;

  @override
  int get hashCode => results.hashCode;

  factory SearchResponses.fromJson(Map<String, dynamic> json) =>
      _$SearchResponsesFromJson(json);

  Map<String, dynamic> toJson() => _$SearchResponsesToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
