openapi: 3.0.2
info:
  title: Recommend API
  description: |-
    The Recommend API lets you generate recommendations with several AI models.
    
    > **Note**: You should use Algolia's [libraries and tools](https://www.algolia.com/doc/guides/getting-started/how-algolia-works/in-depth/ecosystem/) to interact with the Recommend API. Using the HTTP endpoints directly is not covered by the [SLA](https://www.algolia.com/policies/sla/).
    
  version: 1.0.0
components:
  securitySchemes:
    appId:
      $ref: '../common/securitySchemes.yml#/appId'
    apiKey:
      $ref: '../common/securitySchemes.yml#/apiKey'
servers:
  - url: https://{appId}.algolianet.com
    variables:
      appId:
        default: myAppId
  - url: https://{appId}-1.algolianet.com
    variables:
      appId:
        default: myAppId
  - url: https://{appId}-2.algolianet.com
    variables:
      appId:
        default: myAppId
  - url: https://{appId}-3.algolianet.com
    variables:
      appId:
        default: myAppId
  - url: https://{appId}-dsn.algolianet.com
    variables:
      appId:
        default: myAppId
security:
  - appId: []
    apiKey: []
tags:
  - name: recommendations
    x-displayName: Recommend
    description: Manage recommendations.
x-tagGroups:
  - name: General
    tags:
      - recommendations
paths:
  # ######################
  # ### Custom request ###
  # ######################
  /1{path}:
    $ref: '../common/paths/customRequest.yml'

  /1/indexes/*/recommendations:
    $ref: 'paths/getRecommendations.yml'

  /1/indexes/{indexName}/{model}/recommend/rules/{objectID}:
    $ref: 'paths/recommendRule.yml'

  /1/indexes/{indexName}/{model}/task/{taskID}:
    $ref: 'paths/getRecommendStatus.yml'

  /1/indexes/{indexName}/{model}/recommend/rules/search:
    $ref: 'paths/searchRecommendRules.yml'