get:
  tags:
    - configurations
  operationId: getConfigStatus
  summary: Get configuration status.
  description: Report the status of a Query Suggestions index.
  parameters:
    - $ref: '../common/parameters.yml#/IndexName'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              indexName:
                $ref: '../common/schemas/QuerySuggestionsIndexName.yml'
              isRunning:
                type: boolean
                description: Indicates whether the creation or update of the Query Suggestions is in progress.
                example: false
              lastBuiltAt:
                type: string
                description: Timestamp in [ISO-8601](https://wikipedia.org/wiki/ISO_8601) format when the Query Suggestions index was last built.
                example: 2023-07-05T08:03:53Z
              lastSuccessfulBuiltAt:
                type: string
                description: Timestamp in [ISO-8601](https://wikipedia.org/wiki/ISO_8601) format when the Query Suggestions index was last updated successfully.
                example: 2023-07-05T08:03:53Z
              lastSuccessfulBuildDuration:
                type: string
                description: Duration of the last successful build in seconds.
                example: 28
    '401':
      $ref: '../common/responses/Unauthorized.yml'
    '404':
      $ref: '../common/responses/NotFound.yml'
