get:
  tags:
    - configurations
  operationId: getAllConfigs
  summary: List configurations.
  description: List all Query Suggestions configurations of your Algolia application.
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../common/schemas/QuerySuggestionsConfigurationResponse.yml#/QuerySuggestionsConfigurationResponse'
    '401':
      $ref: '../common/responses/Unauthorized.yml'

post:
  tags:
    - configurations
  operationId: createConfig
  summary: Create a configuration.
  description: |
    Create a new Query Suggestions configuration.

    You can have up to 100 configurations per Algolia application.
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../common/schemas/QuerySuggestionsConfigurationWithIndex.yml#/QuerySuggestionsConfigurationWithIndex'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../common/schemas/BaseResponse.yml'
          examples:
            Created:
              summary: Configuration created.
              value:
                'status': 200
                'message': 'Configuration was created, and a new indexing job has been scheduled.'
    '400':
      $ref: '../common/responses/BadRequest.yml'
    '401':
      $ref: '../common/responses/Unauthorized.yml'
    '422':
      $ref: '../common/responses/UnprocessableEntity.yml'
    '500':
      $ref: '../../common/responses/InternalError.yml'
