get:
  tags:
    - configurations
  operationId: getConfig
  summary: Get a configuration.
  description: Get a single Query Suggestions configuration.
  parameters:
    - $ref: '../common/parameters.yml#/IndexName'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../common/schemas/QuerySuggestionsConfigurationResponse.yml'
    '400':
      $ref: '../common/responses/BadRequest.yml'
    '401':
      $ref: '../common/responses/Unauthorized.yml'
    '404':
      $ref: '../common/responses/NotFound.yml'

put:
  tags:
    - configurations
  operationId: updateConfig
  summary: Update a configuration.
  description: Update a QuerySuggestions configuration.
  parameters:
    - $ref: '../common/parameters.yml#/IndexName'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../common/schemas/QuerySuggestionsConfiguration.yml'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../common/schemas/BaseResponse.yml'
          examples:
            Created:
              summary: Configuration created.
              value:
                'status': 200
                'message': 'Configuration was updated, and a new indexing job has been scheduled.'
                
    '401':
      $ref: '../common/responses/Unauthorized.yml'
    '500':
      $ref: '../common/responses/InternalError.yml'

delete:
  tags:
    - configurations
  operationId: deleteConfig
  summary: Delete a configuration.
  description: |
    Delete a Query Suggestions configuration.

    Deleting only removes the configuration and stops updates to the Query Suggestions index.
    The Query Suggestions index itself is not deleted.
  parameters:
    - $ref: '../common/parameters.yml#/IndexName'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BaseResponse'
          examples:
            Created:
              summary: Configuration created.
              value:
                'status': 200
                'message': 'Configuration was deleted with success.'
                
    '401':
      $ref: '../common/responses/Unauthorized.yml'
    '500':
      $ref: '../common/responses/InternalError.yml'
