// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element

import 'package:json_annotation/json_annotation.dart';

part 'ab_tests_variant.g.dart';

@JsonSerializable()
final class AbTestsVariant {
  /// Returns a new [AbTestsVariant] instance.
  const AbTestsVariant({
    required this.index,
    required this.trafficPercentage,
    this.description,
  });

  /// A/B test index.
  @JsonKey(name: r'index')
  final String index;

  /// A/B test traffic percentage.
  @JsonKey(name: r'trafficPercentage')
  final int trafficPercentage;

  /// A/B test description.
  @JsonKey(name: r'description')
  final String? description;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AbTestsVariant &&
          other.index == index &&
          other.trafficPercentage == trafficPercentage &&
          other.description == description;

  @override
  int get hashCode =>
      index.hashCode + trafficPercentage.hashCode + description.hashCode;

  factory AbTestsVariant.fromJson(Map<String, dynamic> json) =>
      _$AbTestsVariantFromJson(json);

  Map<String, dynamic> toJson() => _$AbTestsVariantToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
