// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element

import 'package:json_annotation/json_annotation.dart';

part 'ab_tests_variant_search_params.g.dart';

@JsonSerializable()
final class AbTestsVariantSearchParams {
  /// Returns a new [AbTestsVariantSearchParams] instance.
  const AbTestsVariantSearchParams({
    required this.index,
    required this.trafficPercentage,
    this.description,
    required this.customSearchParameters,
  });

  /// A/B test index.
  @JsonKey(name: r'index')
  final String index;

  /// A/B test traffic percentage.
  @JsonKey(name: r'trafficPercentage')
  final int trafficPercentage;

  /// A/B test description.
  @JsonKey(name: r'description')
  final String? description;

  @JsonKey(name: r'customSearchParameters')
  final Object customSearchParameters;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AbTestsVariantSearchParams &&
          other.index == index &&
          other.trafficPercentage == trafficPercentage &&
          other.description == description &&
          other.customSearchParameters == customSearchParameters;

  @override
  int get hashCode =>
      index.hashCode +
      trafficPercentage.hashCode +
      description.hashCode +
      customSearchParameters.hashCode;

  factory AbTestsVariantSearchParams.fromJson(Map<String, dynamic> json) =>
      _$AbTestsVariantSearchParamsFromJson(json);

  Map<String, dynamic> toJson() => _$AbTestsVariantSearchParamsToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
