/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.recommend

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Edit
 *
 * @param type
 * @param delete Text or patterns to remove from the query string.
 * @param insert Text that should be inserted in place of the removed text inside the query string.
 */
@Serializable
public data class Edit(

  @SerialName(value = "type") val type: EditType? = null,

  /** Text or patterns to remove from the query string. */
  @SerialName(value = "delete") val delete: String? = null,

  /** Text that should be inserted in place of the removed text inside the query string. */
  @SerialName(value = "insert") val insert: String? = null,
)
