/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.recommend

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Personalization
 *
 * @param filtersScore The score of the filters.
 * @param rankingScore The score of the ranking.
 * @param score The score of the event.
 */
@Serializable
public data class Personalization(

  /** The score of the filters. */
  @SerialName(value = "filtersScore") val filtersScore: Int? = null,

  /** The score of the ranking. */
  @SerialName(value = "rankingScore") val rankingScore: Int? = null,

  /** The score of the event. */
  @SerialName(value = "score") val score: Int? = null,
)
