/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.recommend

import kotlinx.serialization.*

/**
 * Strategy to [remove words](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/empty-or-insufficient-results/in-depth/why-use-remove-words-if-no-results/) from the query when it doesn't match any hits.
 */
@Serializable
public enum class RemoveWordsIfNoResults(public val value: kotlin.String) {

  @SerialName(value = "none")
  None("none"),

  @SerialName(value = "lastWords")
  LastWords("lastWords"),

  @SerialName(value = "firstWords")
  FirstWords("firstWords"),

  @SerialName(value = "allOptional")
  AllOptional("allOptional");

  override fun toString(): kotlin.String = value
}
