/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.recommend

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * TrendingItemsQuery
 *
 * @param indexName Algolia index name.
 * @param facetName Facet name for trending models.
 * @param facetValue Facet value for trending models.
 * @param model
 * @param queryParameters
 * @param fallbackParameters
 * @param threshold Recommendations with a confidence score lower than `threshold` won't appear in results. > **Note**: Each recommendation has a confidence score of 0 to 100. The closer the score is to 100, the more relevant the recommendations are.
 * @param maxRecommendations Maximum number of recommendations to retrieve. If 0, all recommendations will be returned.
 */
@Serializable
public data class TrendingItemsQuery(

  /** Algolia index name. */
  @SerialName(value = "indexName") val indexName: String,

  /** Facet name for trending models. */
  @SerialName(value = "facetName") val facetName: String? = null,

  /** Facet value for trending models. */
  @SerialName(value = "facetValue") val facetValue: String? = null,

  @SerialName(value = "model") val model: TrendingItemsModel? = null,

  @SerialName(value = "queryParameters") val queryParameters: SearchParamsObject? = null,

  @SerialName(value = "fallbackParameters") val fallbackParameters: SearchParamsObject? = null,

  /** Recommendations with a confidence score lower than `threshold` won't appear in results. > **Note**: Each recommendation has a confidence score of 0 to 100. The closer the score is to 100, the more relevant the recommendations are.  */
  @SerialName(value = "threshold") val threshold: Int? = null,

  /** Maximum number of recommendations to retrieve. If 0, all recommendations will be returned. */
  @SerialName(value = "maxRecommendations") val maxRecommendations: Int? = null,
) : RecommendationsRequest
