# path
DictionaryName:
  in: path
  name: dictionaryName
  description: Dictionary to search in.
  required: true
  schema:
    $ref: '#/dictionaryType'

dictionaryType:
  type: string
  enum: [plurals, stopwords, compounds]

# misc
language:
  description: >
    [Supported language ISO code](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/handling-natural-languages-nlp/in-depth/supported-languages/).
  example: 'en'
  type: string

standardEntries:
  description: >
    Key-value pairs of [supported language ISO codes](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/handling-natural-languages-nlp/in-depth/supported-languages/) and boolean values.
  additionalProperties: false
  properties:
    plurals:
      $ref: '#/standardEntry'
    stopwords:
      $ref: '#/standardEntry'
    compounds:
      $ref: '#/standardEntry'

standardEntry:
  description: Key-value pair of a language ISO code and a boolean value.
  example: >
    {'fr': false}
  type: object
  nullable: true
  additionalProperties:
    type: boolean
