post:
  tags:
    - Search
  operationId: searchForFacetValues
  x-use-read-transporter: true
  x-cacheable: true
  summary: Search for facet values.
  description: >
    [Search for a facet's values](https://www.algolia.com/doc/guides/managing-results/refine-results/faceting/#search-for-facet-values), optionally restricting the returned values to those contained in records matching other search criteria.

    > **Note**: Pagination isn't supported (`page` and `hitsPerPage` are ignored). By default, the engine returns a maximum of 10 values but you can adjust this with `maxFacetHits`.
  parameters:
    - $ref: '../../../common/parameters.yml#/IndexName'
    - name: facetName
      description: Facet name.
      in: path
      required: true
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          title: searchForFacetValuesRequest
          type: object
          additionalProperties: false
          properties:
            params:
              $ref: '../../../common/schemas/SearchParams.yml#/paramsAsString'
            facetQuery:
              $ref: '../../common/schemas/SearchQuery.yml#/facetQuery'
            maxFacetHits:
              $ref: '../../../common/schemas/IndexSettings.yml#/maxFacetHits'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../../common/schemas/SearchForFacetValuesResponse.yml#/searchForFacetValuesResponse'
    '400':
      $ref: '../../../common/responses/BadRequest.yml'
    '402':
      $ref: '../../../common/responses/FeatureNotEnabled.yml'
    '403':
      $ref: '../../../common/responses/MethodNotAllowed.yml'
    '404':
      $ref: '../../../common/responses/IndexNotFound.yml'
