/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.querysuggestions

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * BaseQuerySuggestionsConfigurationWithIndex
 *
 * @param indexName Query Suggestions index name.
 */
@Serializable
public data class BaseQuerySuggestionsConfigurationWithIndex(

  /** Query Suggestions index name. */
  @SerialName(value = "indexName") val indexName: String,
)
