/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.querysuggestions

import com.algolia.client.exception.AlgoliaClientException
import com.algolia.client.extensions.internal.*
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*
import kotlin.jvm.JvmInline

/**
 * Set the language for deduplicating singular and plural suggestions. If specified, only the more popular form is included.
 *
 * Implementations:
 * - [Boolean] - *[Languages.of]*
 * - [List<String>] - *[Languages.of]*
 */
@Serializable(LanguagesSerializer::class)
public sealed interface Languages {

  @JvmInline
  public value class BooleanValue(public val value: Boolean) : Languages

  @JvmInline
  public value class ListOfStringValue(public val value: List<String>) : Languages

  public companion object {

    /** [Languages] as [Boolean] Value. */
    public fun of(value: Boolean): Languages {
      return BooleanValue(value)
    }

    /** [Languages] as [List<String>] Value. */
    public fun of(value: List<String>): Languages {
      return ListOfStringValue(value)
    }
  }
}

internal class LanguagesSerializer : KSerializer<Languages> {

  override val descriptor: SerialDescriptor = buildClassSerialDescriptor("Languages")

  override fun serialize(encoder: Encoder, value: Languages) {
    when (value) {
      is Languages.BooleanValue -> Boolean.serializer().serialize(encoder, value.value)
      is Languages.ListOfStringValue -> ListSerializer(String.serializer()).serialize(encoder, value.value)
    }
  }

  override fun deserialize(decoder: Decoder): Languages {
    val codec = decoder.asJsonDecoder()
    val tree = codec.decodeJsonElement()

    // deserialize Boolean
    if (tree is JsonPrimitive) {
      try {
        val value = codec.json.decodeFromJsonElement(Boolean.serializer(), tree)
        return Languages.of(value)
      } catch (e: Exception) {
        // deserialization failed, continue
        println("Failed to deserialize Boolean (error: ${e.message})")
      }
    }

    // deserialize List<String>
    if (tree is JsonArray) {
      try {
        val value = codec.json.decodeFromJsonElement(ListSerializer(String.serializer()), tree)
        return Languages.of(value)
      } catch (e: Exception) {
        // deserialization failed, continue
        println("Failed to deserialize List<String> (error: ${e.message})")
      }
    }

    throw AlgoliaClientException("Failed to deserialize json element: $tree")
  }
}
