/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.querysuggestions

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * QuerySuggestionsIndexWithIndexParam
 *
 * @param sourceIndices List of source indices used to generate a Query Suggestions index.
 * @param indexName Index name to target.
 * @param languages De-duplicate singular and plural suggestions. For example, let's say your index contains English content, and that two suggestions “shoe” and “shoes” end up in your Query Suggestions index. If the English language is configured, only the most popular of those two suggestions would remain.
 * @param exclude List of words and patterns to exclude from the Query Suggestions index.
 */
@Serializable
public data class QuerySuggestionsIndexWithIndexParam(

  /** List of source indices used to generate a Query Suggestions index. */
  @SerialName(value = "sourceIndices") val sourceIndices: List<SourceIndex>,

  /** Index name to target. */
  @SerialName(value = "indexName") val indexName: String,

  /** De-duplicate singular and plural suggestions. For example, let's say your index contains English content, and that two suggestions “shoe” and “shoes” end up in your Query Suggestions index. If the English language is configured, only the most popular of those two suggestions would remain. */
  @SerialName(value = "languages") val languages: List<String>? = null,

  /** List of words and patterns to exclude from the Query Suggestions index. */
  @SerialName(value = "exclude") val exclude: List<String>? = null,
)
