/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.predict

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * DeleteModelInstanceResponse
 *
 * @param modelID The ID of the model.
 * @param deletedUntil The date until which you can safely consider the data as being deleted.
 */
@Serializable
public data class DeleteModelInstanceResponse(

  /** The ID of the model. */
  @SerialName(value = "modelID") val modelID: String,

  /** The date until which you can safely consider the data as being deleted. */
  @SerialName(value = "deletedUntil") val deletedUntil: String,
)
