// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element
import 'package:algolia_client_monitoring/src/model/probes_metric.dart';

import 'package:json_annotation/json_annotation.dart';

part 'infrastructure_response_metrics.g.dart';

@JsonSerializable()
final class InfrastructureResponseMetrics {
  /// Returns a new [InfrastructureResponseMetrics] instance.
  const InfrastructureResponseMetrics({
    this.cpuUsage,
    this.ramIndexingUsage,
    this.ramSearchUsage,
    this.ssdUsage,
    this.avgBuildTime,
  });

  /// CPU idleness in %.
  @JsonKey(name: r'cpu_usage')
  final Map<String, List<ProbesMetric>>? cpuUsage;

  /// RAM used for indexing in MB.
  @JsonKey(name: r'ram_indexing_usage')
  final Map<String, List<ProbesMetric>>? ramIndexingUsage;

  /// RAM used for search in MB.
  @JsonKey(name: r'ram_search_usage')
  final Map<String, List<ProbesMetric>>? ramSearchUsage;

  /// Solid-state disk (SSD) usage expressed as % of RAM.  0% means no SSD usage. A value of 50% indicates 32&nbsp;GB SSD usage for a machine with 64&nbsp;RAM.
  @JsonKey(name: r'ssd_usage')
  final Map<String, List<ProbesMetric>>? ssdUsage;

  /// Average build time of the indices in seconds.
  @JsonKey(name: r'avg_build_time')
  final Map<String, List<ProbesMetric>>? avgBuildTime;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InfrastructureResponseMetrics &&
          other.cpuUsage == cpuUsage &&
          other.ramIndexingUsage == ramIndexingUsage &&
          other.ramSearchUsage == ramSearchUsage &&
          other.ssdUsage == ssdUsage &&
          other.avgBuildTime == avgBuildTime;

  @override
  int get hashCode =>
      cpuUsage.hashCode +
      ramIndexingUsage.hashCode +
      ramSearchUsage.hashCode +
      ssdUsage.hashCode +
      avgBuildTime.hashCode;

  factory InfrastructureResponseMetrics.fromJson(Map<String, dynamic> json) =>
      _$InfrastructureResponseMetricsFromJson(json);

  Map<String, dynamic> toJson() => _$InfrastructureResponseMetricsToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
