// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element

import 'package:json_annotation/json_annotation.dart';

part 'time_inner.g.dart';

@JsonSerializable()
final class TimeInner {
  /// Returns a new [TimeInner] instance.
  const TimeInner({
    this.t,
    this.v,
  });

  /// Timestamp in [Unix epoch time](https://wikipedia.org/wiki/Unix_time) in milliseconds.
  @JsonKey(name: r't')
  final int? t;

  /// Time in ms.
  @JsonKey(name: r'v')
  final int? v;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimeInner && other.t == t && other.v == v;

  @override
  int get hashCode => t.hashCode + v.hashCode;

  factory TimeInner.fromJson(Map<String, dynamic> json) =>
      _$TimeInnerFromJson(json);

  Map<String, dynamic> toJson() => _$TimeInnerToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
