name: algolia_client

packages:
  - packages/*

scripts:

  build:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
    description: Build all generated files.

  analyze:
    exec: dart analyze .
    description: Run static analysis checks in all packages

  format:
    exec: dart format .
    description: Run code format in all packages

  fix:
    exec: dart fix --apply
    description: Find and fix static analysis issues in all packages

  lint:
    run: melos fix && melos format
    description: fix and format all packages

  get:
    exec: dart pub get
    description: Run `dart pub get` in all packages

  test:
    exec: dart test
    description: Run `dart test` in all packages

  clear:
    exec: rm -rf .dart_tool
    description: Clear build folders, i.e. `.dart_tool` in all packages

command:
  version:
    hooks:
      post: |
        cd packages && \
        for dir in */ ; do \
          version=$(grep "^version:" "$dir/pubspec.yaml" | sed 's/version: //') && \
          sed -i '' "s/^const packageVersion = .*;$/const packageVersion = '$version';/" "$dir/lib/src/version.dart"; \
        done