/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Authentication input for Basic login with username and password.
 *
 * @param username
 * @param password
 */
@Serializable
public data class AuthBasic(

  @SerialName(value = "username") val username: String,

  @SerialName(value = "password") val password: String,
) : AuthInput
