/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * AuthAlgoliaPartial
 *
 * @param appID Algolia Application ID.
 * @param apiKey Algolia API Key, with the correct rights to push to an index and change settings.
 */
@Serializable
public data class AuthAlgoliaPartial(

  /** Algolia Application ID. */
  @SerialName(value = "appID") val appID: String? = null,

  /** Algolia API Key, with the correct rights to push to an index and change settings. */
  @SerialName(value = "apiKey") val apiKey: String? = null,
) : AuthInputPartial
