/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*

@Serializable
public enum class BigQueryDataType(public val value: kotlin.String) {

  @SerialName(value = "ga4")
  Ga4("ga4"),

  @SerialName(value = "ga360")
  Ga360("ga360");

  override fun toString(): kotlin.String = value
}
