/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*

@Serializable
public enum class RunStatus(public val value: kotlin.String) {

  @SerialName(value = "created")
  Created("created"),

  @SerialName(value = "started")
  Started("started"),

  @SerialName(value = "idled")
  Idled("idled"),

  @SerialName(value = "finished")
  Finished("finished"),

  @SerialName(value = "skipped")
  Skipped("skipped");

  override fun toString(): kotlin.String = value
}
