/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * The input for a `schedule` task whose source is of type `bigquery` and for which extracted data spans a fixed number of days.
 *
 * @param timeframe The timeframe of the extraction, in number of days from today.
 */
@Serializable
public data class ScheduleDateUtilsInput(

  /** The timeframe of the extraction, in number of days from today. */
  @SerialName(value = "timeframe") val timeframe: Int,
) : TaskInput
