/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * SourceCreateResponse
 *
 * @param sourceID The source UUID.
 * @param name
 * @param createdAt Date of creation (RFC3339 format).
 */
@Serializable
public data class SourceCreateResponse(

  /** The source UUID. */
  @SerialName(value = "sourceID") val sourceID: String,

  @SerialName(value = "name") val name: String,

  /** Date of creation (RFC3339 format). */
  @SerialName(value = "createdAt") val createdAt: String,
)
