# path
Clusters:
  name: clusters
  in: path
  required: true
  description: Subset of clusters, separated by comma.
  schema:
    # The `correct` (?) schema should be type array/items string,
    # But the SDK generator expects a string, because it can't replace a list of strings in the URL.
    type: string
    example: 'c1-de,c2-de,c3-de'

MetricInPath:
  name: metric
  in: path
  required: true
  description: |
    Metric to report.

    For more information about the individual metrics, see the response.
    To include all metrics, use `*` as the parameter.
  schema:
    $ref: './enums.yml#/Metric'

PeriodInPath:
  name: period
  in: path
  required: true
  description: |
    Period over which to aggregate the metrics:

    - `minute`. Aggregate the last minute. 1 data point per 10 seconds.
    - `hour`. Aggregate the last hour. 1 data point per minute.
    - `day`. Aggregate the last day. 1 data point per 10 minutes.
    - `week`. Aggregate the last week. 1 data point per hour.
    - `month`. Aggregate the last month. 1 data point per day.
  schema:
    $ref: './enums.yml#/Period'
