# path
ID:
  in: path
  name: id
  description: Unique A/B test ID.
  required: true
  schema:
    type: integer
    example: 390

# misc
index:
  type: string
  description: A/B test index.
  example: 'delcourt_production'

abTestID:
  type: integer
  description: Unique A/B test ID.
  example: 224

endAt:
  type: string
  description: End date timestamp in [ISO-8601](https://wikipedia.org/wiki/ISO_8601) format.
  example: '2023-06-17T00:00:00Z'

createdAt:
  type: string
  description: Creation date timestamp in [ISO-8601](https://wikipedia.org/wiki/ISO_8601) format.
  example: '2023-06-15T15:06:04.249906Z'

updatedAt:
  type: string
  description: Update date timestamp in [ISO-8601](https://wikipedia.org/wiki/ISO_8601) format.
  example: '2023-06-15T15:06:44.400601Z'

name:
  type: string
  description: A/B test name.
  example: 'Custom ranking sales rank test'

description:
  type: string
  description: A/B test description.
  example: 'Current production index'

trafficPercentage:
  type: integer
  description: A/B test traffic percentage.
  example: 60
