// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element

import 'package:json_annotation/json_annotation.dart';

part 'auth_algolia_partial.g.dart';

@JsonSerializable()
final class AuthAlgoliaPartial {
  /// Returns a new [AuthAlgoliaPartial] instance.
  const AuthAlgoliaPartial({
    this.appID,
    this.apiKey,
  });

  /// Algolia Application ID.
  @JsonKey(name: r'appID')
  final String? appID;

  /// Algolia API Key, with the correct rights to push to an index and change settings.
  @JsonKey(name: r'apiKey')
  final String? apiKey;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthAlgoliaPartial &&
          other.appID == appID &&
          other.apiKey == apiKey;

  @override
  int get hashCode => appID.hashCode + apiKey.hashCode;

  factory AuthAlgoliaPartial.fromJson(Map<String, dynamic> json) =>
      _$AuthAlgoliaPartialFromJson(json);

  Map<String, dynamic> toJson() => _$AuthAlgoliaPartialToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
