// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element

import 'package:json_annotation/json_annotation.dart';

part 'auth_basic_partial.g.dart';

@JsonSerializable()
final class AuthBasicPartial {
  /// Returns a new [AuthBasicPartial] instance.
  const AuthBasicPartial({
    this.username,
    this.password,
  });

  @JsonKey(name: r'username')
  final String? username;

  @JsonKey(name: r'password')
  final String? password;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthBasicPartial &&
          other.username == username &&
          other.password == password;

  @override
  int get hashCode => username.hashCode + password.hashCode;

  factory AuthBasicPartial.fromJson(Map<String, dynamic> json) =>
      _$AuthBasicPartialFromJson(json);

  Map<String, dynamic> toJson() => _$AuthBasicPartialToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
