// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element
import 'package:algolia_client_ingestion/src/model/big_commerce_channel.dart';

import 'package:json_annotation/json_annotation.dart';

part 'source_big_commerce.g.dart';

@JsonSerializable()
final class SourceBigCommerce {
  /// Returns a new [SourceBigCommerce] instance.
  const SourceBigCommerce({
    this.storeHash,
    this.channel,
  });

  /// The store hash identifying the store the shopper is signing in to.
  @JsonKey(name: r'storeHash')
  final String? storeHash;

  @JsonKey(name: r'channel')
  final BigCommerceChannel? channel;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceBigCommerce &&
          other.storeHash == storeHash &&
          other.channel == channel;

  @override
  int get hashCode => storeHash.hashCode + channel.hashCode;

  factory SourceBigCommerce.fromJson(Map<String, dynamic> json) =>
      _$SourceBigCommerceFromJson(json);

  Map<String, dynamic> toJson() => _$SourceBigCommerceToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
