// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element
import 'package:json_annotation/json_annotation.dart';

/// Used to sort the Task list endpoint.
@JsonEnum(valueField: 'raw')
enum TaskSortKeys {
  /// Used to sort the Task list endpoint.
  enabled(r'enabled'),

  /// Used to sort the Task list endpoint.
  triggerType(r'triggerType'),

  /// Used to sort the Task list endpoint.
  action(r'action'),

  /// Used to sort the Task list endpoint.
  updatedAt(r'updatedAt'),

  /// Used to sort the Task list endpoint.
  createdAt(r'createdAt');

  const TaskSortKeys(this.raw);
  final dynamic raw;

  dynamic toJson() => raw;

  static TaskSortKeys fromJson(dynamic json) {
    for (final value in values) {
      if (value.raw == json) return value;
    }
    throw ArgumentError.value(json, "raw", "No enum value with that value");
  }

  @override
  String toString() => raw.toString();
}
