name: algolia_client_recommend
version: 0.2.3
description: A sub-package of the AlgoliaSearch library, offering recommend-specific functionalities for enhanced search and discovery in Dart/Flutter apps.
homepage: https://www.algolia.com/doc/
repository: https://github.com/algolia/algoliasearch-client-dart/tree/main/packages/client_recommend
topics:
  - search
  - discovery

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  algolia_client_core: ^0.2.3
  json_annotation: ^4.8.1
  collection: ^1.17.1

dev_dependencies:
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  lints: ^2.1.1
  logging: ^1.2.0
  test: ^1.24.3