QuerySuggestionsConfigurationWithIndex:
  type: object
  description: Query Suggestions configuration.
  required:
    - indexName
    - sourceIndices
  allOf:
    - $ref: '#/baseQuerySuggestionsConfigurationWithIndex'
    - $ref: './QuerySuggestionsConfiguration.yml'

baseQuerySuggestionsConfigurationWithIndex:
  type: object
  additionalProperties: false
  required:
    - indexName
  properties:
    indexName:
      $ref: './QuerySuggestionsIndexName.yml'
