get:
  tags:
    - Dictionaries
  operationId: getDictionarySettings
  description: Get the languages for which [stop words are turned off](#tag/Dictionaries/operation/setDictionarySettings).
  summary: Get stop word settings.
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            title: getDictionarySettingsResponse
            additionalProperties: false
            type: object
            required:
              - disableStandardEntries
            properties:
              disableStandardEntries:
                $ref: 'common/parameters.yml#/standardEntries'
    '400':
      $ref: '../../../common/responses/BadRequest.yml'
    '402':
      $ref: '../../../common/responses/FeatureNotEnabled.yml'
    '403':
      $ref: '../../../common/responses/MethodNotAllowed.yml'
    '404':
      $ref: '../../../common/responses/IndexNotFound.yml'

put:
  tags:
    - Dictionaries
  operationId: setDictionarySettings
  description: Set stop word settings for a specific language.
  summary: Set stop word settings.
  requestBody:
    required: true
    content:
      application/json:
        schema:
          title: dictionarySettingsParams
          type: object
          additionalProperties: false
          description: Enable or turn off the built-in Algolia stop words for a specific language.
          required:
            - disableStandardEntries
          properties:
            disableStandardEntries:
              $ref: 'common/parameters.yml#/standardEntries'
  responses:
    '200':
      $ref: '../../../common/responses/UpdatedAt.yml'
    '400':
      $ref: '../../../common/responses/BadRequest.yml'
    '402':
      $ref: '../../../common/responses/FeatureNotEnabled.yml'
    '403':
      $ref: '../../../common/responses/MethodNotAllowed.yml'
    '404':
      $ref: '../../../common/responses/IndexNotFound.yml'
