name: Version Updates

on:
  push:
    branches:
      - main

jobs:
  check-version:
    name: Version Check
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'chore: release')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Run version check script
        run: .github/scripts/version.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
