// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element

import 'package:json_annotation/json_annotation.dart';

part 'conversion_rate_event.g.dart';

@JsonSerializable()
final class ConversionRateEvent {
  /// Returns a new [ConversionRateEvent] instance.
  const ConversionRateEvent({
    required this.rate,
    required this.trackedSearchCount,
    required this.conversionCount,
    required this.date,
  });

  /// [Click-through rate (CTR)](https://www.algolia.com/doc/guides/search-analytics/concepts/metrics/#click-through-rate).
  // minimum: 0
  // maximum: 1
  @JsonKey(name: r'rate')
  final double rate;

  /// Number of tracked searches. This is the number of search requests where the `clickAnalytics` parameter is `true`.
  @JsonKey(name: r'trackedSearchCount')
  final int trackedSearchCount;

  /// Number of converted clicks.
  @JsonKey(name: r'conversionCount')
  final int conversionCount;

  /// Date of the event in the format YYYY-MM-DD.
  @JsonKey(name: r'date')
  final String date;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversionRateEvent &&
          other.rate == rate &&
          other.trackedSearchCount == trackedSearchCount &&
          other.conversionCount == conversionCount &&
          other.date == date;

  @override
  int get hashCode =>
      rate.hashCode +
      trackedSearchCount.hashCode +
      conversionCount.hashCode +
      date.hashCode;

  factory ConversionRateEvent.fromJson(Map<String, dynamic> json) =>
      _$ConversionRateEventFromJson(json);

  Map<String, dynamic> toJson() => _$ConversionRateEventToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
