// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element
import 'package:algolia_client_analytics/src/model/user_with_date.dart';

import 'package:json_annotation/json_annotation.dart';

part 'get_users_count_response.g.dart';

@JsonSerializable()
final class GetUsersCountResponse {
  /// Returns a new [GetUsersCountResponse] instance.
  const GetUsersCountResponse({
    required this.count,
    required this.dates,
  });

  /// Number of occurrences.
  @JsonKey(name: r'count')
  final int count;

  /// User count.
  @JsonKey(name: r'dates')
  final List<UserWithDate> dates;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GetUsersCountResponse &&
          other.count == count &&
          other.dates == dates;

  @override
  int get hashCode => count.hashCode + dates.hashCode;

  factory GetUsersCountResponse.fromJson(Map<String, dynamic> json) =>
      _$GetUsersCountResponseFromJson(json);

  Map<String, dynamic> toJson() => _$GetUsersCountResponseToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
