// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element
import 'package:algolia_client_analytics/src/model/click_position.dart';

import 'package:json_annotation/json_annotation.dart';

part 'get_click_positions_response.g.dart';

@JsonSerializable()
final class GetClickPositionsResponse {
  /// Returns a new [GetClickPositionsResponse] instance.
  const GetClickPositionsResponse({
    required this.positions,
  });

  /// Click positions.
  @JsonKey(name: r'positions')
  final List<ClickPosition> positions;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GetClickPositionsResponse && other.positions == positions;

  @override
  int get hashCode => positions.hashCode;

  factory GetClickPositionsResponse.fromJson(Map<String, dynamic> json) =>
      _$GetClickPositionsResponseFromJson(json);

  Map<String, dynamic> toJson() => _$GetClickPositionsResponseToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
