get:
  tags:
    - Indices
  operationId: getSettings
  description: Return an object containing an index's [configuration settings](https://www.algolia.com/doc/api-reference/settings-api-parameters/).
  summary: Get index settings.
  parameters:
    - $ref: '../../../common/parameters.yml#/IndexName'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../../../common/schemas/IndexSettings.yml#/indexSettings'
    '400':
      $ref: '../../../common/responses/BadRequest.yml'
    '402':
      $ref: '../../../common/responses/FeatureNotEnabled.yml'
    '403':
      $ref: '../../../common/responses/MethodNotAllowed.yml'
    '404':
      $ref: '../../../common/responses/IndexNotFound.yml'

put:
  tags:
    - Indices
  operationId: setSettings
  description: Update the specified [index settings](https://www.algolia.com/doc/api-reference/settings-api-parameters/). Specifying null for a setting resets it to its default value.
  summary: Update index settings.
  parameters:
    - $ref: '../../../common/parameters.yml#/IndexName'
    - $ref: '../../../common/parameters.yml#/ForwardToReplicas'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../../common/schemas/IndexSettings.yml#/indexSettings'
  responses:
    '200':
      $ref: '../../../common/responses/UpdatedAt.yml'
    '400':
      $ref: '../../../common/responses/BadRequest.yml'
    '402':
      $ref: '../../../common/responses/FeatureNotEnabled.yml'
    '403':
      $ref: '../../../common/responses/MethodNotAllowed.yml'
    '404':
      $ref: '../../../common/responses/IndexNotFound.yml'
