name: Scheduled Release

on:
  schedule:
    - cron: '30 6 * * 2'
  workflow_dispatch:
    inputs:
      fake_input:
        description: input needed to satisfy the yaml linter
        required: false

jobs:
  release:
    name: Scheduled Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          type: minimal
          language: dart # we need the dart deps because we use melos to bump dependencies for its client

      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.ALGOLIA_BOT_TOKEN }}
