/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * ClickPosition
 *
 * @param position Range of positions with the following pattern: - For positions 1 to 10, the number of click events are shown for each position - For positions 11 to 20, all click events are grouped - For positions 21 and up, all click events are grouped.
 * @param clickCount Number of click events.
 */
@Serializable
public data class ClickPosition(

  /** Range of positions with the following pattern: - For positions 1 to 10, the number of click events are shown for each position - For positions 11 to 20, all click events are grouped - For positions 21 and up, all click events are grouped.  */
  @SerialName(value = "position") val position: List<Int>,

  /** Number of click events. */
  @SerialName(value = "clickCount") val clickCount: Int,
)
