/** Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT. */
package com.algolia.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * NoClickRateEvent
 *
 * @param rate [Click-through rate (CTR)](https://www.algolia.com/doc/guides/search-analytics/concepts/metrics/#click-through-rate).
 * @param count Number of tracked _and_ untracked searches (where the `clickAnalytics` parameter isn't `true`).
 * @param noClickCount Number of click events.
 * @param date Date of the event in the format YYYY-MM-DD.
 */
@Serializable
public data class NoClickRateEvent(

  /** [Click-through rate (CTR)](https://www.algolia.com/doc/guides/search-analytics/concepts/metrics/#click-through-rate).  */
  @SerialName(value = "rate") val rate: Double,

  /** Number of tracked _and_ untracked searches (where the `clickAnalytics` parameter isn't `true`). */
  @SerialName(value = "count") val count: Int,

  /** Number of click events. */
  @SerialName(value = "noClickCount") val noClickCount: Int,

  /** Date of the event in the format YYYY-MM-DD. */
  @SerialName(value = "date") val date: String,
)
